2022-08-22 00:58:46,975 INFO io.netty.util.internal.logging.AbstractInternalLogger [lettuce-eventExecutorLoop-1-15] Reconnecting, last destination was localhost/127.0.0.1:6379
2022-08-22 00:59:00,842 WARN io.netty.util.internal.logging.AbstractInternalLogger [lettuce-nioEventLoop-4-2] Cannot reconnect to [localhost/<unresolved>:6379]: Connection closed prematurely
io.lettuce.core.RedisConnectionException: Connection closed prematurely
	at io.lettuce.core.protocol.RedisHandshakeHandler.channelInactive(RedisHandshakeHandler.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
	at io.lettuce.core.ChannelGroupListener.channelInactive(ChannelGroupListener.java:69)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-08-22 00:59:00,880 INFO io.netty.util.internal.logging.AbstractInternalLogger [lettuce-eventExecutorLoop-1-16] Reconnecting, last destination was localhost/<unresolved>:6379
2022-08-22 00:59:00,886 WARN io.netty.util.internal.logging.AbstractInternalLogger [lettuce-nioEventLoop-4-3] Cannot reconnect to [localhost/<unresolved>:6379]: Connection closed prematurely
io.lettuce.core.RedisConnectionException: Connection closed prematurely
	at io.lettuce.core.protocol.RedisHandshakeHandler.channelInactive(RedisHandshakeHandler.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
	at io.lettuce.core.ChannelGroupListener.channelInactive(ChannelGroupListener.java:69)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-08-22 00:59:09,874 INFO io.netty.util.internal.logging.AbstractInternalLogger [lettuce-eventExecutorLoop-1-3] Reconnecting, last destination was localhost/<unresolved>:6379
2022-08-22 00:59:09,877 WARN io.netty.util.internal.logging.AbstractInternalLogger [lettuce-nioEventLoop-4-14] Cannot reconnect to [localhost/<unresolved>:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2022-08-22 00:59:18,072 INFO io.netty.util.internal.logging.AbstractInternalLogger [lettuce-eventExecutorLoop-1-4] Reconnecting, last destination was localhost/<unresolved>:6379
2022-08-22 00:59:18,074 WARN io.netty.util.internal.logging.AbstractInternalLogger [lettuce-nioEventLoop-4-15] Cannot reconnect to [localhost/<unresolved>:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2022-08-22 00:59:34,473 INFO io.netty.util.internal.logging.AbstractInternalLogger [lettuce-eventExecutorLoop-1-5] Reconnecting, last destination was localhost/<unresolved>:6379
2022-08-22 00:59:34,475 WARN io.netty.util.internal.logging.AbstractInternalLogger [lettuce-nioEventLoop-4-16] Cannot reconnect to [localhost/<unresolved>:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2022-08-22 01:00:04,575 INFO io.netty.util.internal.logging.AbstractInternalLogger [lettuce-eventExecutorLoop-1-17] Reconnecting, last destination was localhost/<unresolved>:6379
2022-08-22 01:00:04,578 WARN io.netty.util.internal.logging.AbstractInternalLogger [lettuce-nioEventLoop-4-17] Cannot reconnect to [localhost/<unresolved>:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2022-08-22 01:00:34,677 INFO io.netty.util.internal.logging.AbstractInternalLogger [lettuce-eventExecutorLoop-1-22] Reconnecting, last destination was localhost/<unresolved>:6379
2022-08-22 01:00:34,680 WARN io.netty.util.internal.logging.AbstractInternalLogger [lettuce-nioEventLoop-4-18] Cannot reconnect to [localhost/<unresolved>:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2022-08-22 01:01:04,777 INFO io.netty.util.internal.logging.AbstractInternalLogger [lettuce-eventExecutorLoop-1-24] Reconnecting, last destination was localhost/<unresolved>:6379
2022-08-22 01:01:04,779 WARN io.netty.util.internal.logging.AbstractInternalLogger [lettuce-nioEventLoop-4-19] Cannot reconnect to [localhost/<unresolved>:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2022-08-22 01:01:34,877 INFO io.netty.util.internal.logging.AbstractInternalLogger [lettuce-eventExecutorLoop-1-2] Reconnecting, last destination was localhost/<unresolved>:6379
2022-08-22 01:01:34,880 WARN io.netty.util.internal.logging.AbstractInternalLogger [lettuce-nioEventLoop-4-20] Cannot reconnect to [localhost/<unresolved>:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2022-08-22 01:02:04,972 INFO io.netty.util.internal.logging.AbstractInternalLogger [lettuce-eventExecutorLoop-1-4] Reconnecting, last destination was localhost/<unresolved>:6379
2022-08-22 01:02:04,975 WARN io.netty.util.internal.logging.AbstractInternalLogger [lettuce-nioEventLoop-4-21] Cannot reconnect to [localhost/<unresolved>:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2022-08-22 01:02:35,072 INFO io.netty.util.internal.logging.AbstractInternalLogger [lettuce-eventExecutorLoop-1-6] Reconnecting, last destination was localhost/<unresolved>:6379
2022-08-22 01:02:35,074 WARN io.netty.util.internal.logging.AbstractInternalLogger [lettuce-nioEventLoop-4-22] Cannot reconnect to [localhost/<unresolved>:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2022-08-22 01:03:05,173 INFO io.netty.util.internal.logging.AbstractInternalLogger [lettuce-eventExecutorLoop-1-8] Reconnecting, last destination was localhost/<unresolved>:6379
2022-08-22 01:03:05,176 WARN io.netty.util.internal.logging.AbstractInternalLogger [lettuce-nioEventLoop-4-23] Cannot reconnect to [localhost/<unresolved>:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2022-08-22 01:03:35,275 INFO io.netty.util.internal.logging.AbstractInternalLogger [lettuce-eventExecutorLoop-1-10] Reconnecting, last destination was localhost/<unresolved>:6379
2022-08-22 01:03:35,277 WARN io.netty.util.internal.logging.AbstractInternalLogger [lettuce-nioEventLoop-4-24] Cannot reconnect to [localhost/<unresolved>:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2022-08-22 01:04:05,372 INFO io.netty.util.internal.logging.AbstractInternalLogger [lettuce-eventExecutorLoop-1-12] Reconnecting, last destination was localhost/<unresolved>:6379
2022-08-22 01:04:05,373 WARN io.netty.util.internal.logging.AbstractInternalLogger [lettuce-nioEventLoop-4-1] Cannot reconnect to [localhost/<unresolved>:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2022-08-22 01:04:35,472 INFO io.netty.util.internal.logging.AbstractInternalLogger [lettuce-eventExecutorLoop-1-14] Reconnecting, last destination was localhost/<unresolved>:6379
2022-08-22 01:04:35,474 WARN io.netty.util.internal.logging.AbstractInternalLogger [lettuce-nioEventLoop-4-2] Cannot reconnect to [localhost/<unresolved>:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2022-08-22 01:05:05,573 INFO io.netty.util.internal.logging.AbstractInternalLogger [lettuce-eventExecutorLoop-1-16] Reconnecting, last destination was localhost/<unresolved>:6379
2022-08-22 01:05:05,574 WARN io.netty.util.internal.logging.AbstractInternalLogger [lettuce-nioEventLoop-4-3] Cannot reconnect to [localhost/<unresolved>:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2022-08-22 01:05:35,674 INFO io.netty.util.internal.logging.AbstractInternalLogger [lettuce-eventExecutorLoop-1-18] Reconnecting, last destination was localhost/<unresolved>:6379
2022-08-22 01:05:35,675 WARN io.netty.util.internal.logging.AbstractInternalLogger [lettuce-nioEventLoop-4-4] Cannot reconnect to [localhost/<unresolved>:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2022-08-22 01:06:05,777 INFO io.netty.util.internal.logging.AbstractInternalLogger [lettuce-eventExecutorLoop-1-20] Reconnecting, last destination was localhost/<unresolved>:6379
2022-08-22 01:06:05,779 WARN io.netty.util.internal.logging.AbstractInternalLogger [lettuce-nioEventLoop-4-5] Cannot reconnect to [localhost/<unresolved>:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2022-08-22 01:06:35,883 INFO io.netty.util.internal.logging.AbstractInternalLogger [lettuce-eventExecutorLoop-1-22] Reconnecting, last destination was localhost/<unresolved>:6379
2022-08-22 01:06:35,884 WARN io.netty.util.internal.logging.AbstractInternalLogger [lettuce-nioEventLoop-4-6] Cannot reconnect to [localhost/<unresolved>:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2022-08-22 01:07:05,972 INFO io.netty.util.internal.logging.AbstractInternalLogger [lettuce-eventExecutorLoop-1-24] Reconnecting, last destination was localhost/<unresolved>:6379
2022-08-22 01:07:05,974 WARN io.netty.util.internal.logging.AbstractInternalLogger [lettuce-nioEventLoop-4-7] Cannot reconnect to [localhost/<unresolved>:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2022-08-22 01:07:36,072 INFO io.netty.util.internal.logging.AbstractInternalLogger [lettuce-eventExecutorLoop-1-2] Reconnecting, last destination was localhost/<unresolved>:6379
2022-08-22 01:07:36,073 WARN io.netty.util.internal.logging.AbstractInternalLogger [lettuce-nioEventLoop-4-8] Cannot reconnect to [localhost/<unresolved>:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2022-08-22 01:08:06,180 INFO io.netty.util.internal.logging.AbstractInternalLogger [lettuce-eventExecutorLoop-1-4] Reconnecting, last destination was localhost/<unresolved>:6379
2022-08-22 01:08:06,181 WARN io.netty.util.internal.logging.AbstractInternalLogger [lettuce-nioEventLoop-4-9] Cannot reconnect to [localhost/<unresolved>:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2022-08-22 01:08:36,273 INFO io.netty.util.internal.logging.AbstractInternalLogger [lettuce-eventExecutorLoop-1-6] Reconnecting, last destination was localhost/<unresolved>:6379
2022-08-22 01:08:36,274 WARN io.netty.util.internal.logging.AbstractInternalLogger [lettuce-nioEventLoop-4-10] Cannot reconnect to [localhost/<unresolved>:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
